# Generated by Django 2.2.3 on 2019-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('hotel_name', models.TextField()),
                ('price', models.IntegerField()),
                ('exclusions', models.TextField()),
                ('inclusions', models.TextField()),
                ('day_wise_desc', models.TextField()),
            ],
        ),
    ]
