# Generated by Django 2.2.3 on 2019-07-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='exclusions',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='inclusions',
        ),
    ]
