# Generated by Django 2.2.3 on 2019-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20190729_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='nights',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
